"""Obecné anglické tooltipy pro /en/ stránky (parlamentní pojmy)."""

from __future__ import annotations

# Delší fráze nahoře (stejné pravidlo jako v glossary.py).
GLOSSARY_EN_CORE: tuple[tuple[str, str], ...] = (
    ("The Chamber of Deputies", "The lower house of the Czech Parliament. Where laws are debated and voted on."),
    ("Czech Television Council", "The body that oversees Czech Television and picks its leadership."),
    ("CT Council", "The body that oversees Czech Television and picks its leadership."),
    ("Supreme Audit Office", "The state's top watchdog for public spending."),
    ("Constitutional Court", "The highest court for constitutional matters. In 2020 it also ruled on Andrej Babiš's conflict of interest."),
    ("Mandate and Immunity Committee", "The Chamber's referee: conflicts of interest, discipline, or handing an MP to the police."),
    ("Building Permits Act", "Law on construction permits. Critics call it the lex developer."),
    ("building law", "Rules for construction permits. The coalition wants faster approvals; the opposition warns about weaker municipalities."),
    ("Building Act", "Rules for construction permits. The coalition wants faster approvals; the opposition warns about weaker municipalities."),
    ("construction procedure", "The official process for getting a building permit. The debate is how to speed it up without breaking legal certainty."),
    ("construction management", "The official process for getting a building permit. The debate is how to speed it up without breaking legal certainty."),
    ("building authorities", "Municipal or regional offices that decide on building permits. The bill wants to merge and digitise them."),
    ("building authority", "Municipal or regional office that decides on building permits. The bill wants to merge and digitise them."),
    ("construction authorities", "Municipal or regional offices that decide on building permits. The bill wants to merge and digitise them."),
    ("municipal architect", "Municipal official who checks whether buildings fit the local plan."),
    ("city architects", "Municipal officials who check whether buildings fit the local plan."),
    ("zoning plan", "Municipal document that sets where and what may be built."),
    ("land-use plan", "Municipal document that sets where and what may be built."),
    ("municipalities with extended jurisdiction", "Larger towns that run some state administration, including building offices, for smaller villages nearby."),
    ("Plant Protection Act", "Law on crop spraying and plant protection, partly driven by EU rules."),
    (
        "sent the Plant Protection Act back to second reading",
        "Senators or MPs send the bill back for another round of detailed debate and amendments.",
    ),
    ("sent back to second reading", "The bill goes back for another round of detailed debate and amendments."),
    ("returned to second reading", "The bill goes back for another round of detailed debate and amendments."),
    ("back to second reading", "The bill goes back for another round of detailed debate and amendments."),
    ("to second reading", "The bill moves to the stage where MPs propose changes and vote on specific parts."),
    ("passed at first reading", "The Chamber decided to keep working on the bill. Nothing is approved yet."),
    ("failed at first reading", "The Chamber stopped the bill at the first hurdle. It will not move forward."),
    ("stopped it at first reading", "The Chamber stopped the bill at the first hurdle. It will not move forward."),
    ("fell at first reading", "The Chamber stopped the bill at the first hurdle. It will not move forward."),
    ("passed first reading", "The Chamber decided to keep working on the bill. Nothing is approved yet."),
    ("first reading passed", "The Chamber decided to keep working on the bill. Nothing is approved yet."),
    ("first reading of", "The Chamber decides whether to keep working on a bill. Nothing is approved yet."),
    ("from first reading", "The Chamber decides whether to keep working on a bill. Nothing is approved yet."),
    ("at third reading", "Final vote on a bill in The Chamber of Deputies. Then it may go to the president for signature."),
    ("at second reading", "MPs propose changes and vote on specific parts of the bill."),
    ("at first reading", "The Chamber decides whether to keep working on a bill. Nothing is approved yet."),
    ("lex developer", "Critics' nickname for the building law: they say it favours big developers."),
    ("super benefit", "Plan to merge several social benefits into one system with one application. Not a new payment on top."),
    ("electronic sales records", "Every receipt once reported to the state how much you earned."),
    ("EET (electronic sales records)", "Every receipt once reported to the state how much you earned."),
    ("third reading", "Final vote on a bill in The Chamber of Deputies. Then it may go to the president for signature."),
    ("second reading", "MPs propose changes and vote on specific parts of the bill."),
    ("first reading", "The Chamber decides whether to keep working on a bill. Nothing is approved yet."),
    ("final vote", "Final vote on a bill in The Chamber of Deputies."),
    ("legislative urgency", "Fast-track mode where bills move quicker than usual."),
    ("extraordinary session", "A sitting called outside the regular calendar when something is urgent."),
    ("extraordinary meeting", "A sitting called outside the regular calendar when something is urgent."),
    ("extraordinary meetings", "Sittings called outside the regular calendar when something is urgent."),
    ("procedural motion", "Not about the law itself, but about how the debate will run."),
    ("procedural motions", "Not about the law itself, but about how the debate will run."),
    ("suspension of the session", "MPs take a break and promise to come back to it."),
    ("suspension", "MPs take a break and promise to come back to it."),
    ("vote of no confidence", "An attempt to send the government into political retirement before it leaves on its own."),
    ("no confidence", "A vote on whether the government still has majority support."),
    ("no-confidence", "A vote on whether the government still has majority support."),
    ("vote of confidence", "A vote on whether the government still has majority support."),
    ("interpellation (parliamentary Q&A session)", "Parliamentary Q&A: MPs question ministers on the record."),
    ("interpellations (parliamentary Q&A sessions)", "Parliamentary Q&A: MPs question ministers on the record."),
    ("interpellation", "Parliamentary Q&A session. MPs question ministers on the record."),
    ("Beneš decrees", "Post-war decrees of President Beneš on property and status of Germans and Hungarians after WWII."),
    ("Sudeten German Landsmanschaft", "Organisation of Sudeten Germans expelled after WWII and their descendants."),
    ("Sudeten German landsmanschaft", "Organisation of Sudeten Germans expelled after WWII and their descendants."),
    ("Sudeten German compatriots", "Sudeten Germans expelled after WWII and their descendants."),
    ("Sudeten German", "Germans expelled from Czechoslovakia after WWII and their descendants; often debated in connection with the landsmanschaft."),
    ("landsmanschaft", "Organisation of Sudeten Germans expelled after WWII and their descendants."),
    ("TV and radio licence fee", "Annual fee for Czech Television and Czech Radio."),
    ("concession fees", "Annual fee for Czech Television and Czech Radio."),
    ("VZP reserves", "Money VZP saved on top of requirements. Politicians often fight over redistributing it."),
    ("VZP surpluses", "Money VZP earned on top. Politicians often want to redistribute it among insurers."),
    ("third pillar", "Voluntary pension savings on top of the state pension."),
    ("benefits digitalisation", "Moving social benefit applications and admin online."),
    ("minimum social contribution", "The lowest mandatory amount a self-employed person pays into social insurance."),
    ("self-employed person", "Someone who runs their own business and pays social and health insurance themselves."),
    ("OSVČ", "Self-employed person: a freelancer or sole trader who pays their own insurance."),
    ("person with a disability (OZP)", "A person with a health-related disability."),
    ("OZP", "Person with a health-related disability."),
    ("Labour Office", "Pays unemployment benefits, housing support, and other social help."),
    ("Labour Offices", "Pays unemployment benefits, housing support, and other social help."),
    ("Prague Public Transport Company", "Prague city transport. Central to the Dozimetr corruption case."),
    ("public service media", "Czech Television and Czech Radio."),
    ("Dozimetr", "Corruption scandal around Prague's public transport company, linked to STAN figures and public contracts."),
    ("Dozimeter", "Corruption scandal around Prague's public transport company, linked to STAN figures and public contracts."),
    ("Agrofert", "One of the largest Czech holdings. Babiš moved it into trust funds; dispute is whether he still influences it."),
    ("Agrofert subsidies", "State and EU money paid to companies in the Agrofert group. The opposition says the prime minister should not decide on them."),
    ("trust funds", "Legal structure Babiš used to hold Agrofert. The dispute is whether he still controls the company."),
    ("Babišism", "Kupka's term for a style of rule where the state serves whoever holds power, not citizens."),
    ("babyism", "Kupka's term for a style of rule where the state serves whoever holds power, not citizens."),
    ("conflict of interest", "When a politician decides on matters that may affect their own business or personal interests."),
    ("post-1989 cartel", "Babiš's term for established parties and elites after 1989, which he says coordinate against him."),
    ("voucher privatisation", "Privatisation of state assets in the 1990s using voucher booklets."),
    ("VZP management board", "Group of people who decide how the largest health insurer runs."),
    ("Collection of Laws", "Official place where adopted laws are published."),
    ("online lawmaking", "Project to prepare and publish laws electronically."),
    ("legislative process", "A bill's journey from proposal to the president's signature."),
    ("civil service law", "Rules for how state officials work."),
    ("stenographic record", "Verbatim transcript of everything said in The Chamber of Deputies."),
    ("organisational committee", "Group that plans the session programme."),
    ("mobility allowance", "Money for people with health limitations for transport and travel."),
    ("housing support", "State help with rent or a mortgage for people who cannot afford housing alone."),
    ("municipal contact point", "Local branch where citizens handle paperwork."),
    ("state honours", "Medals and honours awarded by the president or recommended by The Chamber of Deputies."),
    ("quorum", "Minimum number of MPs present without which an official vote cannot happen."),
    ("MP immunity", "Protection from criminal prosecution without The Chamber of Deputies' consent."),
    ("EU regulation", "Rule that applies directly in all EU member states."),
    ("transposition", "Turning EU rules into Czech laws."),
    ("harmonisation with EU", "Rewriting Czech rules so Brussels does not need to take notes."),
    ("deficit", "When the state spends more than it collects. A bit like a pub running on credit."),
    ("state final account", "Annual balance sheet: how much the state spent and whether the numbers add up."),
    ("budget rule", "Law setting how the state may plan and spend money."),
    ("budget brakes", "Rules that remind the state to hit the brakes when spending gets too fast."),
    ("fiscal rules", "Rules that remind the state the credit card is not bottomless."),
    ("party club", "Group of MPs from one party in The Chamber of Deputies."),
    ("committee stage", "Smaller working groups of MPs where bills are handled in detail."),
    ("committee", "Smaller working group of MPs where bills are handled in detail."),
    ("obstruction", "When people talk at length mainly so voting gets delayed."),
    ("obstructions", "When people talk at length mainly so voting gets delayed."),
    ("obstructive", "When remarks are used mainly to delay voting rather than debate the substance."),
    ("obstructing", "When people talk at length mainly so voting gets delayed."),
    ("obstructed", "When debate was delayed mainly by long speeches or procedural moves."),
    ("obstruct", "To delay debate or voting, often with long speeches or procedural moves."),
    ("rules of procedure", "The rulebook for MPs: who may speak, when, and for how long."),
    ("Rules of Procedure", "The rulebook for MPs: who may speak, when, and for how long."),
    ("our rules of procedure", "The rulebook for MPs: who may speak, when, and for how long."),
    ("amendment", "Attempt to change part of a bill without writing a new one."),
    ("amendments", "Attempts to change parts of a bill without writing a new one."),
    ("Senate returned the bill", "Senators sent the proposal back with a note to try again."),
    ("returned by the Senate", "Senators sent the proposal back with a note to try again."),
    ("The Senate returned", "Senators sent the proposal back with a note to try again."),
    ("resolution", "A statement or decision of The Chamber of Deputies. Not a law."),
    ("resolutions", "Statements or decisions of The Chamber of Deputies. Not laws."),
    ("NKÚ", "Supreme Audit Office: checks how the state spends public money."),
    ("SFŽP", "State Environmental Fund: pays for cleaners, insulation, drought projects, and similar."),
    ("Čapí hnízdo", "Long-running case around an EU subsidy for a farm linked to Andrej Babiš."),
    ("EET", "Electronic sales records. Every receipt once reported to the state how much you earned."),
    ("investment funds", "Companies that manage investors' money, including pension savings."),
    ("pension savings", "Voluntary savings for retirement alongside the state pension."),
    ("minimum contribution", "Smallest monthly amount a self-employed person must pay into social insurance."),
    ("social insurance", "Payments for pensions, sick pay, and unemployment support."),
    ("(ANO)", "Movement ANO 2011, Andrej Babiš's party."),
    ("(ODS)", "Civic Democratic Party."),
    ("(KDU-ČSL)", "Christian and Democratic Union, Czechoslovak People's Party."),
    ("(STAN)", "Mayors and Independents."),
    ("(SPD)", "Freedom and Direct Democracy, Tomio Okamura's party."),
    ("(Piráti)", "Czech Pirate Party."),
    ("(TOP 09)", "Liberal-conservative party."),
    ("(Motoristé)", "Motorists' party led by Petr Macinka, focused on drivers' rights."),
    ("STAN", "Mayors and Independents."),
    ("grémium", "Meeting of party club chairs where they agree the agenda and procedure."),
    ("gavel", "Symbol of the chair's authority; ringing it ends debate and calls MPs to vote."),
    ("the gong", "Sound signal by which the chair ends debate and calls MPs to vote."),
    ("gong", "Sound signal by which the chair ends debate and calls MPs to vote."),
    ("banner", "Placard in the chamber. MPs use it to make a point; it must not cover the speaker."),
    ("secret ballot", "MPs vote anonymously; nobody sees who supported whom."),
    ("Deputy Speaker", "Deputy who stands in for the Speaker when running meetings."),
    ("Deputy Speakers", "Deputies who stand in for the Speaker when running meetings."),
    ("Deputy Speaker's seat", "Deputy who stands in for the Speaker when running meetings."),
    ("Speaker", "Presiding officer who runs Chamber sessions."),
    ("verifiers", "Two MPs who check that the session followed the rules."),
    ("verifier", "One of two MPs who check that the session followed the rules."),
    ("election commission", "Group of MPs that organises and supervises all votes inside The Chamber."),
    # --- actors, institutions, debate ---
    ("coalition", "Parties governing together and trying to sound like one voice."),
    ("opposition", "Parties not in government, watching whether the cabinet cooks with someone else's money."),
    ("Senate", "The upper chamber of Parliament. It reviews laws passed by The Chamber of Deputies."),
    ("Senate veto", "Senators send a bill back or suggest changes. MPs can override them."),
    ("presidential veto", "The president sends a bill back and asks MPs to think again."),
    ("self-employed people", "Freelancers and sole traders who pay their own social and health insurance."),
    ("self-employed persons", "Freelancers and sole traders who pay their own social and health insurance."),
    ("self-employed", "Freelancers and sole traders who pay their own social and health insurance."),
    ("government bill", "A bill the cabinet sends to The Chamber of Deputies. It often moves faster than opposition proposals."),
    ("government's position", "The cabinet's official view on a bill. MPs get it as a separate Chamber document."),
    ("Senate bill", "A bill the Senate sends to The Chamber of Deputies for approval or amendment."),
    ("Chamber document", "Official number of a bill or paper in The Chamber of Deputies."),
    ("Chamber print", "Official number of a bill or paper in The Chamber of Deputies."),
    ("parliamentary press", "Official number of a bill or paper in The Chamber of Deputies."),
    ("rapporteur", "MP from a committee who explains a bill to the Chamber and recommends how to vote."),
    ("rapporteurs", "MPs at the table who explain a bill and answer questions before the vote."),
    ("female rapporteur", "MP from a committee who explains a bill to the Chamber and recommends how to vote."),
    ("female rapporteurs", "MPs from committees who explain a bill to the Chamber and recommend how to vote."),
    ("general debate", "Phase when MPs speak about the whole bill, not individual paragraphs."),
    ("detailed debate", "Phase when MPs read and discuss specific paragraphs of a bill or resolution."),
    ("in the detailed debate", "Phase when MPs read and discuss specific paragraphs of a bill or resolution."),
    ("at the detailed debate", "Phase when MPs read and discuss specific paragraphs of a bill or resolution."),
    ("committee chair", "MP who runs a committee's meetings and sets its programme."),
    ("state budget", "The state's annual spending and revenue plan. Debated in several readings."),
    ("agenda", "The list of topics The Chamber of Deputies will debate and vote on that day."),
    ("agenda of the meeting", "The list of topics The Chamber of Deputies will debate and vote on that day."),
    ("meeting agenda", "The list of topics The Chamber of Deputies will debate and vote on that day."),
    ("living minimum", "Basic income threshold the state uses to calculate some benefits."),
    ("subsistence minimum", "Lowest income line used to work out whether someone qualifies for benefits."),
    ("existential minimum", "Lowest income line used to work out whether someone qualifies for benefits."),
    ("secret election", "MPs vote anonymously on paper ballots in an urn, not by pressing a card button."),
    ("fast-track", "Fast-track mode where bills move quicker than usual."),
    ("fast track", "Fast-track mode where bills move quicker than usual."),
    ("accelerated procedure", "Fast-track mode where bills move quicker than usual."),
    ("abbreviated mode", "Fast-track mode where bills move quicker than usual."),
    ("abbreviated meeting", "Fast-track mode where bills move quicker than usual."),
    ("investigation committee", "Chamber team with special powers to investigate a specific scandal."),
    ("crop spraying", "Rules on how farmers may treat crops with plant protection products."),
    ("QR codes", "Square codes on ballots: blind voters can scan them to know who they are voting for."),
    ("QR code", "Square code on a ballot: blind voters can scan it to know who they are voting for."),
    ("Czech Statehood Day", "Public holiday on 28 October, when state honours are often awarded."),
    ("proportional representation", "Committee seats shared according to how many MPs each party has."),
    ("nomination law", "Law on who may sit on boards of state-owned companies."),
    ("constitutional law", "Highest-rank bill. Needs a special majority in The Chamber of Deputies and Senate consent."),
    ("state honour", "Medal or honour awarded by the president or recommended by The Chamber of Deputies."),
    ("harmonisation", "Rewriting Czech rules so Brussels does not need to take notes."),
    ("eLegislativa", "Electronic system for drafting and processing laws. Meant to unify work across offices and The Chamber."),
    ("online legislation", "Project to prepare and publish laws electronically."),
    ("immunity", "Protection from criminal prosecution without The Chamber of Deputies' consent."),
    ("VZP", "The largest health insurer in the Czech Republic."),
    ("PWD card", "Card for people with a health-related disability. Used for benefits and services."),
    ("PWD", "Person with a health-related disability."),
    ("benefits", "State payments such as housing support, child benefit, or unemployment help."),
    ("the super benefit", "Plan to merge several social benefits into one system with one application."),
    ("transition to super benefit", "Gradual switch from old benefits to the merged super benefit system."),
    # --- rounds, adjournment, plenary ---
    (
        "motion to adjourn until tomorrow",
        "Not about the law itself: MPs vote on whether to stop for the day and come back later.",
    ),
    ("motion to adjourn the debate", "Not about the law itself: MPs vote on whether to pause and return to the topic later."),
    ("motion to adjourn", "Not about the law itself: MPs vote on whether to pause and return to the topic later."),
    ("meeting adjourned", "MPs paused the sitting and promised to return to it later."),
    ("was adjourned", "MPs paused the sitting and promised to return to it later."),
    ("adjournment from", "The sitting was paused earlier and continues on a later date."),
    ("adjournment", "MPs pause the sitting or debate and promise to return to it later."),
    ("adjourned", "MPs paused the sitting or debate and promised to return to it later."),
    ("adjourn until tomorrow", "MPs stop for the day and promise to return to the same item later."),
    ("adjourn the debate", "MPs pause debate on the current item and promise to return to it."),
    ("adjourn", "MPs pause the sitting or debate and promise to return to it later."),
    ("debate adjourned", "MPs paused debate on the current item and promised to return to it."),
    ("debate suspended", "MPs paused debate on the current item and promised to return to it."),
    ("suspension of debate", "MPs paused debate on the current item and promised to return to it."),
    ("suspension of the item", "MPs paused one agenda item and promised to return to it later."),
    ("session interrupted", "MPs paused the sitting and promised to return to it."),
    ("postponement", "The item is moved to a later date. Today ends without a decision on the substance."),
    ("postponed to the next session", "The item is moved to a later sitting. Today ends without a decision on the substance."),
    ("deferred to the next session", "The item is moved to a later sitting. Today ends without a decision on the substance."),
    ("not today", "The item is moved to a later date. Today ends without a decision on the substance."),
    ("first round of", "First stage in The Chamber: for a bill, deciding whether to keep working on it."),
    ("in the first round", "First stage in The Chamber: for a bill, deciding whether to keep working on it."),
    ("first round", "First stage in The Chamber: for a bill, deciding whether to keep working on it."),
    ("second round of", "Second stage: MPs propose changes and vote on specific parts of the bill."),
    ("in the second round", "Second stage: MPs propose changes and vote on specific parts of the bill."),
    ("second round", "Second stage: MPs propose changes and vote on specific parts of the bill."),
    ("third round of", "Final vote on a bill in The Chamber of Deputies. Then it may go to the president for signature."),
    ("in the third round", "Final vote on a bill in The Chamber of Deputies. Then it may go to the president for signature."),
    ("third round", "Final vote on a bill in The Chamber of Deputies. Then it may go to the president for signature."),
    ("passed at third reading", "The Chamber approved the bill in the final vote. Next stop is usually the president's signature."),
    ("failed at third reading", "The Chamber rejected the bill in the final vote. The proposal stops here."),
    ("stopped at second reading", "The Chamber ended work on the bill before the final vote."),
    ("passed at second reading", "The bill cleared the stage where MPs propose changes. One more round may follow."),
    ("full Chamber", "All 200 MPs in the main hall, not just a committee."),
    ("plenary session", "All 200 MPs in the main hall, not just a committee."),
    ("plenary", "All 200 MPs in the main hall, not just a committee."),
    ("plenum", "All 200 MPs in the main hall, not just a committee."),
    ("constituent session", "First sitting after elections: leadership and committees are set up. No laws yet."),
    ("constituting session", "First sitting after elections: leadership and committees are set up. No laws yet."),
    ("inaugural session", "First sitting after elections: leadership and committees are set up. No laws yet."),
    # --- government, confidence, caretaker ---
    ("asking for confidence", "The prime minister formally requests that The Chamber confirm the government has majority support."),
    ("request for confidence", "The prime minister formally requests that The Chamber confirm the government has majority support."),
    ("motion of confidence", "A vote on whether the government still has majority support."),
    ("confidence in his government", "A vote on whether MPs still support the prime minister's cabinet."),
    ("confidence in the government", "A vote on whether MPs still support the cabinet."),
    ("debate on confidence", "MPs discuss whether the government deserves their support before the vote."),
    ("caretaker government", "A cabinet after elections or a fall that only runs the state until a new one is sworn in."),
    ("in caretaker capacity", "The government only manages the state with limited powers until a new cabinet takes over."),
    ("caretaker mode", "The government only manages the state with limited powers until a new cabinet takes over."),
    ("caretaker", "The government only manages the state with limited powers until a new cabinet takes over."),
    ("Babiš's government", "Cabinet led by Andrej Babiš and his Movement ANO."),
    ("Babiš government", "Cabinet led by Andrej Babiš and his Movement ANO."),
    ("Fiala's government", "Cabinet led by Petr Fiala (ODS) in the 2021-2025 term."),
    ("Fiala government", "Cabinet led by Petr Fiala (ODS) in the 2021-2025 term."),
    # --- institutions, media, funds ---
    ("General Health Insurance Company", "The largest health insurer in the Czech Republic. Politicians often debate its finances and management."),
    ("State Environmental Fund", "Pays for cleaners, insulation, drought projects, and similar environmental spending."),
    ("Czech Radio", "Public radio broadcaster alongside Czech Television."),
    ("Czech Television", "Public TV broadcaster overseen by the CT Council."),
    ("Constitutional Court ruling", "Decision of the highest court for constitutional matters."),
    ("decision of the Constitutional Court", "Ruling of the highest court for constitutional matters."),
    ("Constitution of the Czech Republic", "The country's basic law. Changes need a special majority in The Chamber and Senate consent."),
    ("the Constitution", "The country's basic law. Changes need a special majority in The Chamber and Senate consent."),
    ("constitution", "The country's basic law. Changes need a special majority in The Chamber and Senate consent."),
    ("electronic Collection of Laws", "Official digital register of adopted laws. The system is still not fully finished."),
    ("Collection of Laws and international treaties", "Official register where adopted laws and treaties are published."),
    ("investment management company", "Firm that manages investors' money under rules set by law."),
    ("investment company", "Firm that manages investors' money under rules set by law."),
    ("Prague transport company", "Prague city transport. Central to the Dozimetr corruption case."),
    ("DPP", "Prague Public Transport Company. Central to the Dozimetr corruption case."),
    ("Stork's Nest", "Long-running case around an EU subsidy for a farm linked to Andrej Babiš."),
    ("Storks Nest", "Long-running case around an EU subsidy for a farm linked to Andrej Babiš."),
    # --- CT Council, grémium, committees ---
    ("election to the CT Council", "Vote on who will sit on the body that oversees Czech Television."),
    ("CT Council election", "Vote on who will sit on the body that oversees Czech Television."),
    ("vote on the CT Council", "Vote on who will sit on the body that oversees Czech Television."),
    ("proposal from the grémium", "Agenda item agreed in advance by party club chairs."),
    ("grémium agreement", "Deal among party club chairs on the order of business or a break."),
    ("from the grémium", "According to an agreement among party club chairs."),
    ("party club chairs", "Leaders of each party's MP group. They meet in the grémium."),
    ("party clubs", "Groups of MPs from one party in The Chamber of Deputies."),
    ("to committees", "Bills go to smaller working groups of MPs for detailed handling."),
    ("in committees", "Smaller working groups of MPs where bills are handled in detail."),
    ("committees", "Smaller working groups of MPs where bills are handled in detail."),
    ("committee chairs", "MPs who run committee meetings and set their programme."),
    ("Mandate committee", "The Chamber's referee: conflicts of interest, discipline, or handing an MP to the police."),
    ("Immunity committee", "The Chamber's referee: conflicts of interest, discipline, or handing an MP to the police."),
    ("Deputy Speaker of The Chamber", "Deputy who stands in for the Speaker when running meetings."),
    ("Deputy Speakers of The Chamber", "Deputies who stand in for the Speaker when running meetings."),
    ("order of business", "The list of topics The Chamber will debate and vote on that day."),
    ("session programme", "The list of topics The Chamber will debate and vote on that day."),
    ("programme of the session", "The list of topics The Chamber will debate and vote on that day."),
    # --- law variants, EU, finance ---
    ("building law", "Law on construction permits. Critics call it the lex developer."),
    ("construction bill", "Proposal to change rules for building houses, extensions, and roads."),
    ("construction permits", "Official permission to start building. The current debate is about how fast offices must decide."),
    ("Rules of Procedure Act", "Law setting how The Chamber of Deputies runs its debates and votes."),
    ("Rules of Procedure", "The rulebook for MPs: who may speak, when, and for how long."),
    ("returned by senators", "Senators sent the proposal back with a note to try again."),
    ("Senate sent back", "Senators sent the proposal back with a note to try again."),
    ("override the Senate", "The Chamber can pass a bill again after senators reject or amend it."),
    ("override senators", "The Chamber can pass a bill again after senators reject or amend it."),
    ("harmonisation with European law", "Rewriting Czech rules so Brussels does not need to take notes."),
    ("harmonisation with EU law", "Rewriting Czech rules so Brussels does not need to take notes."),
    ("European Union regulation", "Rule that applies directly in all EU member states."),
    ("fiscal limits", "Rules that remind the state the credit card is not bottomless."),
    ("fiscal ceiling", "Rules that remind the state the credit card is not bottomless."),
    ("budget deficit", "When the state spends more than it collects. A bit like a pub running on credit."),
    ("state budget for", "The state's annual spending and revenue plan."),
    ("legislative emergency", "Fast-track mode where the Speaker shortens deadlines so a bill can move very quickly."),
    ("shortened mode", "Fast-track mode where bills move quicker than usual."),
    ("shortened consideration", "Fast-track mode where bills move quicker than usual."),
    ("accelerated consideration", "Fast-track mode where bills move quicker than usual."),
    ("fast-track consideration", "Fast-track mode where bills move quicker than usual."),
    ("voucher debabišisation", "Proposal to sell Agrofert shares to citizens via vouchers so the prime minister would not be in conflict of interest."),
    ("coupon debabišisation", "Proposal to sell Agrofert shares to citizens via vouchers so the prime minister would not be in conflict of interest."),
    ("coupon privatisation", "Privatisation of state assets in the 1990s using voucher booklets."),
    # --- benefits, social ---
    ("child benefit", "State payment to families with children."),
    ("unemployment benefit", "Money from the Labour Office when someone loses their job."),
    ("social benefit", "State payment such as housing support, child benefit, or unemployment help."),
    ("social benefits", "State payments such as housing support, child benefit, or unemployment help."),
    ("minimum social insurance", "The lowest mandatory amount a self-employed person pays into social insurance."),
    ("minimum social contributions", "The lowest mandatory amount a self-employed person pays into social insurance."),
    ("pension third pillar", "Voluntary pension savings on top of the state pension."),
    ("digitalisation of benefits", "Moving social benefit applications and admin online."),
    # --- parties (plain names) ---
    ("Movement ANO 2011", "Andrej Babiš's party."),
    ("Movement ANO", "Andrej Babiš's party."),
    ("Civic Democratic Party", "Conservative party led for years by Petr Fiala."),
    ("Mayors and Independents", "Party of mayors and regional politicians, acronym STAN."),
    ("Czech Pirate Party", "Progressive party focused on transparency and digital state."),
    ("Freedom and Direct Democracy", "Tomio Okamura's party, acronym SPD."),
    ("Christian and Democratic Union", "People's party with Christian-democratic tradition, acronym KDU-ČSL."),
    ("Motorists for Themselves", "Party led by Petr Macinka, focused on drivers' rights."),
    ("Motorists", "Motorists for Themselves, party led by Petr Macinka."),
    ("Motorist", "Motorists for Themselves, party led by Petr Macinka."),
    ("TOP 09", "Liberal-conservative party."),
    # --- people (first mention tooltips) ---
    ("Alena Schillerová", "Former finance minister, now ANO MP. Often speaks on budget and taxes."),
    ("Marian Jurečka", "Minister of Labour and Social Affairs and KDU-ČSL leader."),
    ("Jakub Michálek", "Leader of the Pirate party club in The Chamber of Deputies."),
    ("Radim Fiala", "Leader of the SPD party club in The Chamber of Deputies."),
    ("Andrej Babiš", "Leader of Movement ANO and prime minister in the current term."),
    ("Petr Fiala", "ODS leader and prime minister in the 2021-2025 term."),
    ("Tomio Okamura", "Leader of SPD and often Speaker or Deputy Speaker of The Chamber."),
    # --- debate theatre ---
    ("from the sidelines", "The corridor beside the chamber where MPs talk off-mic."),
    ("the sidelines", "The corridor beside the chamber where MPs talk off-mic."),
    ("banners", "Placards in the chamber. MPs use them to make a point; they must not cover the speaker."),
    ("rang the gavel", "The chair ended debate and called MPs to vote."),
    ("called the vote", "The chair ended debate and asked MPs to press their cards or cast ballots."),
    ("public vote", "MPs vote openly; everyone can see who supported whom."),
    ("open vote", "MPs vote openly; everyone can see who supported whom."),
    ("secret voting", "MPs vote anonymously; nobody sees who supported whom."),
    ("filibuster", "When people talk at length mainly so voting gets delayed."),
    ("no-confidence motion", "An attempt to send the government into political retirement before it leaves on its own."),
    ("MPs registered", "Deputies who have checked in for the sitting and count toward quorum."),
    ("registered MPs", "Deputies who have checked in for the sitting and count toward quorum."),
    ("deputies present", "MPs physically in the hall at the time of the vote."),
    ("MPs present", "Deputies physically in the hall at the time of the vote."),
)

SLOVNIK_BOX_EN: tuple[tuple[str, str], ...] = (
    ("Budget brakes", "budget brakes"),
    ("Fiscal rules", "fiscal rules"),
    ("Deficit", "deficit"),
    ("Amendment", "amendment"),
    ("First reading", "first reading"),
    ("Second reading", "second reading"),
    ("Third reading", "third reading"),
    ("Procedural motion", "procedural motion"),
    ("Suspension of the session", "suspension"),
    ("Senate returned the bill", "returned by the Senate"),
    ("Resolution", "resolution"),
    ("Quorum", "quorum"),
    ("Committee", "committee"),
    ("EET", "EET"),
    ("lex developer", "lex developer"),
    ("Czech Television Council", "Czech Television Council"),
    ("landsmanschaft", "landsmanschaft"),
    ("Harmonisation with EU", "harmonisation"),
    ("Mobility allowance", "mobility allowance"),
    ("OZP", "OZP"),
    ("Minimum contribution", "minimum contribution"),
    ("Pension savings", "pension savings"),
    ("Investment funds", "investment fund"),
    ("Housing support", "housing support"),
    ("State honours", "state honours"),
    ("Labour Office", "Labour Office"),
    ("Extraordinary session", "extraordinary"),
    ("Adjournment", "adjourn"),
    ("First round", "first round"),
    ("Second round", "second round"),
    ("Third round", "third round"),
    ("Plenum", "plenum"),
    ("Constitution", "constitution"),
    ("Caretaker government", "caretaker"),
    ("CT Council election", "CT Council election"),
    ("Rules of Procedure", "Rules of Procedure"),
    ("Investment company", "investment company"),
    ("Child benefit", "child benefit"),
    ("Public vote", "public vote"),
    ("Grémium", "grémium"),
)

POSLANECINY_PREKLAD_EN: tuple[tuple[str, str], ...] = (
    ("First reading", "Nothing decided yet"),
    ("Second reading", "Drilling into the paragraphs"),
    ("Third reading", "Last chance, then yes or no"),
    ("Procedural motion", "A fight over how to fight"),
    ("Suspension of the session", "Break"),
    ("Senate returned the bill", "Senate said: try again"),
    ("Resolution", "A message"),
    ("Interpellation", "Ministers explain themselves"),
    ("Committee", "Mini-Chamber"),
    ("Conflict of interest", "When a politician handles their own business"),
    ("Budget brakes", "Brake on the state credit card"),
    ("Fiscal rules", "Rules that the credit card is not bottomless"),
    ("Deficit", "Spent more than they collected"),
    ("Obstruction", "Talking so nobody votes"),
    ("Vote of no confidence", "Sending the government home"),
    ("Amendment", "I'd write that bit differently"),
    ("Transposition", "Copying Brussels into Czech law"),
    ("Quorum", "Not enough MPs in the hall to vote"),
    ("Lex developer", "Law for big builders"),
    ("Postponement", "Not today"),
    ("First round", "First pass in The Chamber"),
    ("Second round", "Drilling into the paragraphs"),
    ("Third round", "Last chance, then yes or no"),
    ("Adjournment", "Break until tomorrow"),
    ("Plenum", "All 200 in the hall"),
    ("Caretaker government", "Cabinet with one foot out the door"),
)
