"""Obecné anglické tooltipy pro /en/ stránky (parlamentní pojmy)."""

from __future__ import annotations

# Delší fráze nahoře (stejné pravidlo jako v glossary.py).
GLOSSARY_EN_CORE: tuple[tuple[str, str], ...] = (
    ("The Chamber of Deputies", "The lower house of the Czech Parliament. Where laws are debated and voted on."),
    ("Czech Television Council", "The body that oversees Czech Television and picks its leadership."),
    ("CT Council", "The body that oversees Czech Television and picks its leadership."),
    ("Supreme Audit Office", "The state's top watchdog for public spending."),
    ("Constitutional Court", "The highest court for constitutional matters. In 2020 it also ruled on Andrej Babiš's conflict of interest."),
    ("Mandate and Immunity Committee", "The Chamber's referee: conflicts of interest, discipline, or handing an MP to the police."),
    ("Building Permits Act", "Law on construction permits. Critics call it the lex developer."),
    ("Plant Protection Act", "Law on crop spraying and plant protection, partly driven by EU rules."),
    ("lex developer", "Critics' nickname for the building law: they say it favours big developers."),
    ("super benefit", "Plan to merge several social benefits into one system with one application. Not a new payment on top."),
    ("electronic sales records", "Every receipt once reported to the state how much you earned."),
    ("EET (electronic sales records)", "Every receipt once reported to the state how much you earned."),
    ("third reading", "Final vote on a bill in The Chamber of Deputies. Then it may go to the president for signature."),
    ("second reading", "MPs propose changes and vote on specific parts of the bill."),
    ("first reading", "The Chamber decides whether to keep working on a bill. Nothing is approved yet."),
    ("final vote", "Final vote on a bill in The Chamber of Deputies."),
    ("legislative urgency", "Fast-track mode where bills move quicker than usual."),
    ("extraordinary session", "A sitting called outside the regular calendar when something is urgent."),
    ("procedural motion", "Not about the law itself, but about how the debate will run."),
    ("suspension of the session", "MPs take a break and promise to come back to it."),
    ("vote of no confidence", "An attempt to send the government into political retirement before it leaves on its own."),
    ("no confidence", "A vote on whether the government still has majority support."),
    ("vote of confidence", "A vote on whether the government still has majority support."),
    ("interpellation (parliamentary Q&A session)", "Parliamentary Q&A: MPs question ministers on the record."),
    ("interpellations (parliamentary Q&A sessions)", "Parliamentary Q&A: MPs question ministers on the record."),
    ("interpellation", "Parliamentary Q&A session. MPs question ministers on the record."),
    ("Beneš decrees", "Post-war decrees of President Beneš on property and status of Germans and Hungarians after WWII."),
    ("Sudeten German landsmanschaft", "Organisation of Sudeten Germans expelled after WWII and their descendants."),
    ("landsmanschaft", "Organisation of Sudeten Germans expelled after WWII and their descendants."),
    ("TV and radio licence fee", "Annual fee for Czech Television and Czech Radio."),
    ("concession fees", "Annual fee for Czech Television and Czech Radio."),
    ("VZP reserves", "Money VZP saved on top of requirements. Politicians often fight over redistributing it."),
    ("VZP surpluses", "Money VZP earned on top. Politicians often want to redistribute it among insurers."),
    ("third pillar", "Voluntary pension savings on top of the state pension."),
    ("benefits digitalisation", "Moving social benefit applications and admin online."),
    ("minimum social contribution", "The lowest mandatory amount a self-employed person pays into social insurance."),
    ("self-employed person", "Someone who runs their own business and pays social and health insurance themselves."),
    ("OSVČ", "Self-employed person: a freelancer or sole trader who pays their own insurance."),
    ("person with a disability (OZP)", "A person with a health-related disability."),
    ("OZP", "Person with a health-related disability."),
    ("Labour Office", "Pays unemployment benefits, housing support, and other social help."),
    ("Prague Public Transport Company", "Prague city transport. Central to the Dozimetr corruption case."),
    ("public service media", "Czech Television and Czech Radio."),
    ("Dozimetr", "Corruption scandal around Prague's public transport company, linked to STAN figures and public contracts."),
    ("Dozimeter", "Corruption scandal around Prague's public transport company, linked to STAN figures and public contracts."),
    ("Agrofert", "One of the largest Czech holdings. Babiš moved it into trust funds; dispute is whether he still influences it."),
    ("conflict of interest", "When a politician decides on matters that may affect their own business or personal interests."),
    ("post-1989 cartel", "Babiš's term for established parties and elites after 1989, which he says coordinate against him."),
    ("voucher privatisation", "Privatisation of state assets in the 1990s using voucher booklets."),
    ("VZP management board", "Group of people who decide how the largest health insurer runs."),
    ("Collection of Laws", "Official place where adopted laws are published."),
    ("online lawmaking", "Project to prepare and publish laws electronically."),
    ("legislative process", "A bill's journey from proposal to the president's signature."),
    ("civil service law", "Rules for how state officials work."),
    ("stenographic record", "Verbatim transcript of everything said in The Chamber of Deputies."),
    ("organisational committee", "Group that plans the session programme."),
    ("mobility allowance", "Money for people with health limitations for transport and travel."),
    ("housing support", "State help with rent or a mortgage for people who cannot afford housing alone."),
    ("municipal contact point", "Local branch where citizens handle paperwork."),
    ("state honours", "Medals and honours awarded by the president or recommended by The Chamber of Deputies."),
    ("quorum", "Minimum number of MPs present without which an official vote cannot happen."),
    ("MP immunity", "Protection from criminal prosecution without The Chamber of Deputies' consent."),
    ("EU regulation", "Rule that applies directly in all EU member states."),
    ("transposition", "Turning EU rules into Czech laws."),
    ("harmonisation with EU", "Rewriting Czech rules so Brussels does not need to take notes."),
    ("deficit", "When the state spends more than it collects. A bit like a pub running on credit."),
    ("state final account", "Annual balance sheet: how much the state spent and whether the numbers add up."),
    ("budget rule", "Law setting how the state may plan and spend money."),
    ("budget brakes", "Rules that remind the state to hit the brakes when spending gets too fast."),
    ("fiscal rules", "Rules that remind the state the credit card is not bottomless."),
    ("party club", "Group of MPs from one party in The Chamber of Deputies."),
    ("committee stage", "Smaller working groups of MPs where bills are handled in detail."),
    ("committee", "Smaller working group of MPs where bills are handled in detail."),
    ("obstruction", "When people talk at length mainly so voting gets delayed."),
    ("rules of procedure", "The rulebook for MPs: who may speak, when, and for how long."),
    ("amendment", "Attempt to change part of a bill without writing a new one."),
    ("Senate returned the bill", "Senators sent the proposal back with a note to try again."),
    ("resolution", "A statement or decision of The Chamber of Deputies. Not a law."),
    ("NKÚ", "Supreme Audit Office: checks how the state spends public money."),
    ("SFŽP", "State Environmental Fund: pays for cleaners, insulation, drought projects, and similar."),
    ("Čapí hnízdo", "Long-running case around an EU subsidy for a farm linked to Andrej Babiš."),
    ("EET", "Electronic sales records. Every receipt once reported to the state how much you earned."),
    ("investment funds", "Companies that manage investors' money, including pension savings."),
    ("pension savings", "Voluntary savings for retirement alongside the state pension."),
    ("minimum contribution", "Smallest monthly amount a self-employed person must pay into social insurance."),
    ("social insurance", "Payments for pensions, sick pay, and unemployment support."),
    ("(ANO)", "Movement ANO 2011, Andrej Babiš's party."),
    ("(ODS)", "Civic Democratic Party."),
    ("(KDU-ČSL)", "Christian and Democratic Union, Czechoslovak People's Party."),
    ("(STAN)", "Mayors and Independents."),
    ("(SPD)", "Freedom and Direct Democracy, Tomio Okamura's party."),
    ("(Piráti)", "Czech Pirate Party."),
    ("(TOP 09)", "Liberal-conservative party."),
    ("(Motoristé)", "Motorists' party led by Petr Macinka, focused on drivers' rights."),
    ("STAN", "Mayors and Independents."),
    ("grémium", "Meeting of party club chairs where they agree the agenda and procedure."),
    ("gavel", "Sound signal by which the chair ends debate and calls MPs to vote."),
    ("banner", "Placard in the chamber. MPs use it to make a point; it must not cover the speaker."),
    ("secret ballot", "MPs vote anonymously; nobody sees who supported whom."),
    ("Deputy Speaker", "Deputy who stands in for the Speaker when running meetings."),
    ("Speaker", "Presiding officer who runs Chamber sessions."),
    ("verifiers", "Two MPs who check that the session followed the rules."),
    ("election commission", "Group of MPs that organises and supervises all votes inside The Chamber."),
)

SLOVNIK_BOX_EN: tuple[tuple[str, str], ...] = (
    ("Budget brakes", "budget brakes"),
    ("Fiscal rules", "fiscal rules"),
    ("Deficit", "deficit"),
    ("Amendment", "amendment"),
    ("First reading", "first reading"),
    ("Second reading", "second reading"),
    ("Third reading", "third reading"),
    ("Procedural motion", "procedural motion"),
    ("Suspension of the session", "suspension"),
    ("Senate returned the bill", "returned by the Senate"),
    ("Resolution", "resolution"),
    ("Quorum", "quorum"),
    ("Committee", "committee"),
    ("EET", "EET"),
    ("lex developer", "lex developer"),
    ("Czech Television Council", "Czech Television Council"),
    ("landsmanschaft", "landsmanschaft"),
    ("Harmonisation with EU", "harmonisation"),
    ("Mobility allowance", "mobility allowance"),
    ("OZP", "OZP"),
    ("Minimum contribution", "minimum contribution"),
    ("Pension savings", "pension savings"),
    ("Investment funds", "investment fund"),
    ("Housing support", "housing support"),
    ("State honours", "state honours"),
    ("Labour Office", "Labour Office"),
    ("Extraordinary session", "extraordinary"),
)

POSLANECINY_PREKLAD_EN: tuple[tuple[str, str], ...] = (
    ("First reading", "Nothing decided yet"),
    ("Second reading", "Drilling into the paragraphs"),
    ("Third reading", "Last chance, then yes or no"),
    ("Procedural motion", "A fight over how to fight"),
    ("Suspension of the session", "Break"),
    ("Senate returned the bill", "Senate said: try again"),
    ("Resolution", "A message"),
    ("Interpellation", "Ministers explain themselves"),
    ("Committee", "Mini-Chamber"),
    ("Conflict of interest", "When a politician handles their own business"),
    ("Budget brakes", "Brake on the state credit card"),
    ("Fiscal rules", "Rules that the credit card is not bottomless"),
    ("Deficit", "Spent more than they collected"),
    ("Obstruction", "Talking so nobody votes"),
    ("Vote of no confidence", "Sending the government home"),
    ("Amendment", "I'd write that bit differently"),
    ("Transposition", "Copying Brussels into Czech law"),
)
